circleci/image-builder

- circleci-provision-scripts/ruby.sh
$RUBY_VERSION got conflicted with probably the same name of env var used by rvm.
```
+ sudo -H -u ubuntu bash
+ install_ruby_version 2.2.2
+ RUBY_VERSION=2.2.2
+ RUBYGEMS_MAJOR_RUBY_VERSION=2
+ cat
+ as_user RUBY_VERSION=2.2.2 RUBYGEMS_MAJOR_RUBY_VERSION=2 bash
+ sudo -H -u ubuntu RUBY_VERSION=2.2.2 RUBYGEMS_MAJOR_RUBY_VERSION=2 bash
Installing Ruby version: 2.2.2
Using /home/ubuntu/.rvm/gems/ruby-2.2.1
ruby-2.2.1 - #downloading rubygems-2.5.1
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  458k  100  458k    0     0  10.0M      0 --:--:-- --:--:-- --:--:-- 10.1M
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.2.1 - #extracting rubygems-2.5.1....
ruby-2.2.1 - #removing old …
```
> Avoid variable conflicting

- circleci-provision-scripts/mysql.sh
Discovered the library header is missing in https://circleci.zendesk.com/agent/tickets/1296
> Add libmysqld-dev to install mysql2 gem

- circleci-provision-scripts/base.sh
- circleci-provision-scripts/misc.sh
We want to have 2.7.4 for https://ma.ttias.be/remote-code-execution-git-versions-client-server-2-7-1-cve-2016-2324-cve-2016-2315/ , since that fix doesn't seem to have been backported yet.
Also, `xargs apt-get install` is slow, so let's do that less.
> Use a PPA for git, `xargs apt-get install` less

- README.md
This was pointing to the image that requires having a copy of this repository to access circleci-install.
> Fix build image path

- circle.yml
Pulling latest unprivileged doesn't help with docker caching - as the privileged just recently built image has all the layers we care about.
> pulling latest unprivileged doesn't help

- circleci-provision-scripts/docker.sh
- tests/Dockerfile
- tests/unit/services.bats
`curl -L -s https://get.docker.io/ | sh` will install the latest docker and breaks upstart scripts that circleci docker relies on.
> Fix docker version

- circle.yml
Docker hub sometimes returns internal server error for no obvious reasons. I asked the support but the only reasonable workaround is re-pushing.
> Retry docker push in case it fails

- Dockerfile
- circle.yml
- pkg-versions.sh
The motivation here is stop using Github release tag to push LXC image because it doesn't fit into how we test container image.
**Before**
- build docker image at master
- pull the docker image locally
- once the image fines, create Github release that triggers a build
- the build will push LXC image to S3 which will be shipped to production
The problem here is that there is no guarantee that the build image created by Github release is exactly the same as the image that's already tested. In practice, it will be the same image thanks to Docker cache, but still not guaranteed.
**After**
- build docker image at master
- push LXC image to S3
- pull the docker image locally
- once the image fines, ship the LXC image to production
> Changing workflow2

- circleci-provision-scripts/nodejs.sh
- circleci-provision-scripts/php.sh
- circleci-provision-scripts/python.sh
- circleci-provision-scripts/ruby.sh
This is necessary otherwise we need to build the image from scratch when we add a new version of language because `apt-get upadte` for packagecloud is cached and doesn't detect newly created version.
> Always running apt-get update for packagecloud repository

- Dockerfile
- circle.yml
- pkg-versions.sh
- tests/unit/pkg-versions.bats
- tests/unit/python.bats
We are calling `pyenv local` inside `pkg-versions.sh`. This sets the local python version to `2.7.11`. The problem is that CircleCI uses `pyenv global` to switch python version in circle.yml but `pyenv local` takes precedence over `pyenv global` and our customers cannot change the python version.
> Don't run python local

- circleci-provision-scripts/postgres.sh
- pkg-versions.sh
- tests/unit/services.bats
We were installing both 9.4 and 9.5 on the Trusty container image but this has never been our intention. 9.4 is the version that we wanted to install but 9.5 was also installed as a part of postgis dependency.
It looks majority of our customers want 9.5, though. So, we'll be updating to 9.5 and not to install 9.4 at all.
> Postgresql 9.5

- circleci-provision-scripts/mysql.sh
- tests/unit/services.bats
Updating mysql to 5.7 break some builds because empty password for root is set only for socket but not for network access. See https://www.percona.com/blog/2016/03/16/change-user-password-in-mysql-5-7-with-plugin-auth_socket/
> MySQL 5.7 empty root password

- Dockerfile
- circleci-install
- circleci-provision-scripts/nodejs.sh
- circleci-provision-scripts/php.sh
- circleci-provision-scripts/python.sh
- circleci-provision-scripts/ruby.sh
We want to avoid expensive apt-get update to install a version when `circleci-install` is used standalone.
> Add RUN_APT_UPDATE flag

- Dockerfile
- circleci-install
- circleci-provision-scripts/android-ndk.sh
- circleci-provision-scripts/android-sdk.sh
- circleci-provision-scripts/clojure.sh
- circleci-provision-scripts/nodejs.sh
- circleci-provision-scripts/php.sh
- circleci-provision-scripts/postgres.sh
- circleci-provision-scripts/python.sh
- circleci-provision-scripts/ruby.sh
- circleci-provision-scripts/scala.sh
When using `circleci-install` standalone, the default verbose output is obtrusive, so disabling verbose output by default and can be enabled with `VERBOSE` flag.
Also removing redundant shellopts set in many places and consolidated into once place that we can export to child processes.
> Use xtrace (-x) shellopts only when VERBOSE=true

- Dockerfile
- circleci-provision-scripts/misc.sh
After some testing on my own builds I'm reasonably confident that this fixes the issue with Redis not starting up and staying up on 14.04.
Various searches suggest that getting Upstart to manage Redis in 14.04 is the most reliable option. The specific source for the changes I've made is here: https://gist.github.com/bdotdub/714533
> Fix redis not starting up and staying up

- circleci-provision-scripts/android-sdk.sh
- targets/ubuntu-14.04-XL/Dockerfile
- targets/ubuntu-14.04-XXL-enterprise/Dockerfile
- targets/ubuntu-14.04-XXL/Dockerfile
- Removing sys-img-armeabi-v7a-android-23 because it doesn't exist anymore
- Adding more SDK's
> Android image 

- Makefile
- scripts/release-LXC-container
This runs the release-LXC-container script as part of our enterprise CD process. In the past, the release-LXC-container script has arbitrarily timed out for certain regions, because the file size is so large. So, this also retries each individual upload up to three times.
> Automatically LXCify and upload enterprise containters

- Makefile
We've been using the wrong bucket for too long and this means that
instances which start outside of us-east-1 are doing cross-region copies
of the container image when they boot. This causes many us-east-2 and
us-west-2 container hosts to fail to become ready because the download
times out.
> [CIRCLE-2115] Put the 14.04 images in the correct bucket.

- circleci-provision-scripts/java.sh
Current version defaults to now-deprecated TLS v1.0, rev needed to use v1.2
> Rev Oracle JDK 7 to more recent version

- aws-vm.json
- circleci-provision-scripts/docker.sh
- provision.sh
Currently image-builder installs the latest version of Docker onto the generated AMI; there isn't a way to specify a specific version to be installed. There is an issue with building Docker images with generated AMIs that use `18.06.2-ce` (the current latest Docker version); building results in the error `OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown`.
Here is an example of the error output when running the Docker image building test in [realitycheck](https://github.com/CircleCI-Public/realitycheck/blob/master/.circleci/config.yml#L45):
This issue is not encountered when building with the default vm-service AMI (that is used when a custom AMI is not …
> Allow specifying of docker version to install and avoid issues with using the current latest Docker version (18.06.2)
