Vagrantfile
Fix https://github.com/circleci/image-builder-prototype/issues/1
=> Use override for aws provider box

Dockerfile, circleci-provision-scripts/clojure.sh, circleci-provision-scripts/go.sh, circleci-provision-scripts/java.sh, circleci-provision-scripts/nodejs.sh, circleci-provision-scripts/php.sh, circleci-provision-scripts/python.sh, circleci-provision-scripts/ruby.sh, circleci-provision-scripts/scala.sh
Add more debugging for subshells, and delete temporary files.
=> Subshell debugging

Dockerfile, circleci-provision-scripts/base.sh, circleci-provision-scripts/misc.sh
circleci/circle uses bsdtar for deployment
=> Add bsdtar and tidying up packages

Dockerfile, circle.yml, circleci-install, circleci-provision-scripts/circleci-specific.sh, circleci-provision-scripts/nodejs.sh, circleci-provision-scripts/php.sh, circleci-provision-scripts/python.sh, circleci-provision-scripts/ruby.sh
Installing Ruby, Python, PHP, Nodejs from pre-compiled package: https://packagecloud.io/circleci/trusty
Everything will be installed under `/opt/circleci` and *vm and *env will refer the installed packages with symbolic link.
We also install more versions for each language in this change. We will install all major and minor version of the latest patch release.
=> Start using https://github.com/kimh/package-builder

Dockerfile, circleci-provision-scripts/base.sh, circleci-provision-scripts/misc.sh
Installing missing things a few beta users brought up
=> Install missing bits

circleci-provision-scripts/ruby.sh
Will fix https://github.com/circleci/image-builder/issues/38 https://github.com/circleci/image-builder/issues/37
=> Fix ruby issues

Dockerfile
=> Adding node.js 5.5.0 ~1st pass at image making

circleci-provision-scripts/base.sh, circleci-provision-scripts/firefox.sh, circleci-provision-scripts/misc.sh, docker-export
* Option to install a specific firefox version.
* Option to install `prince` and the closure compiler.
* s/git-core/git/g
* Fix the interpreter directive in docker-export
=> misc additions

README.md
It was missing the container name
=> Fix CONTAINER_SSH_PORT command

Dockerfile, circleci-provision-scripts/php.sh
Adding new Node version ~ going to add more language versions with next push.
=> Adding Node 5.7.0

Dockerfile
@kimh Please merge if/when the build passes :+1:
=> First trusty image

circleci-provision-scripts/python.sh
Sometimes app uses `pyenv global system`.
=> Installing system pip

Dockerfile, tests/unit/php.bats
- Adding PHP 7.0.4 and remove 7.0.2
- Rebuilding from the scrtach in order to install newest circleci-php packages
that pear/pecl and libphp enabled
- Testing tests
=> PHP updates

Dockerfile, circle.yml, pkg-versions.sh, tests/unit/versions.bats
This is the first step for build-image doc automation. I also need know all installed versions inside container for the next image update.
=> Generating versions.json

Dockerfile, circleci-provision-scripts/chrome.sh, pkg-versions.sh
Updating chrome driver is unrelated but realized that I have to do that before the next build image shipping.
=> Fix gcloud version

Dockerfile, circleci-provision-scripts/mysql.sh
Using multiple ADD and ENV at one line to reduce layers
=> Dockerfile diet

Dockerfile, circle.yml, circleci-provision-scripts/base.sh, circleci-provision-scripts/chrome.sh, circleci-provision-scripts/firefox.sh, circleci-provision-scripts/java.sh, circleci-provision-scripts/qt.sh, circleci-provision-scripts/scala.sh, tests/unit/java.bats, tests/unit/nodejs.bats, tests/unit/php.bats, tests/unit/python.bats, tests/unit/qt.bats
Added
Python 2.7.12
Python 3.5.2
PHP 7.0.11
Nodejs 4.5.0
Sbt 0.13.10 0.13.11 0.13.12
Qt 5.5
Removed
PHP 7.0.3
Updated
Firefox 46.0 -> 47.0.1
Google Chrome 50 -> 53
Chrome Driver 2.21 -> 2.23
Java8 8u40 -> 8u102
Bug fix
Unable to switch to openjdk7
=> Image Update 201610-01

circleci-provision-scripts/mysql.sh, circleci-provision-scripts/postgres.sh
Slight improvements for cleaning up files and processes started within the container build.
=> Minor Postgres/mysql cleanup tweaks

scripts/release-LXC-container
This adds a script for deploying LXC images to our infrastructure.
=> Add LXC deploy script

README.md
Addresses: https://github.com/circleci/image-builder/issues/79
=> Add note about including mysql / postgres

circleci-provision-scripts/misc.sh, provision.sh
With socat and nsenter, minikube can be run from binary in GCE VM
=> Add socat and nsenter

.circleci/config.yml, circleci-provision-scripts/android-sdk.sh, circleci-provision-scripts/base.sh, circleci-provision-scripts/curl.sh, circleci-provision-scripts/gcloud.sh, circleci-provision-scripts/heroku.sh, circleci-provision-scripts/java.sh, circleci-provision-scripts/mysql.sh, circleci-provision-scripts/nodejs.sh, targets/ubuntu-14.04-XXL/Dockerfile, tests/unit/test_helper_java.bash, tests/unit/ubuntu-14.04-XXL/go.bats, tests/unit/ubuntu-14.04-XXL/java.bats, tests/unit/ubuntu-14.04-XXL/nodejs.bats, tests/unit/ubuntu-14.04-XXL/php.bats, tests/unit/ubuntu-14.04-XXL/ruby.bats, tests/unit/ubuntu-14.04-XXL/services.bats
https://discuss.circleci.com/t/ubuntu-14-04-build-image-update-201710-01/17609/2
=> Image update 20171001
